name: Build and deploy React app to Azure Web App - dotwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up the Node.js environment
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install Dependencies
        run: |
          npm install --force
          npm install serve --force

      # Build the React application
      - name: Build React App
        run: CI=false npm run build

      # Prepare the artifact for deployment
      - name: Zip the Build Directory
        run: |
          cd build
          zip -r ../release.zip ./*

      # Upload the build artifact for the deployment job
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      # Download the artifact from the build job
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: react-app

      # Unzip the artifact to prepare for deployment
      - name: Unzip Artifact
        run: unzip release.zip -d ./wwwroot

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dotwebapp'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1564DEA97C304E7392544B762EA5B291 }}
          package: './wwwroot'

      # Optional: Verify deployment
      - name: Check Deployed Directory
        run: ls -l ./wwwroot
